In [2]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [25]:
#loading dataset to pandas dataframe
dataset = pd.read_csv('USA_Housing.csv')

In [26]:
dataset.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   
4      59982.197226             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  \
0                          4.09     23086.800503  1.059034e+06   
1                          3.09     40173.072174  1.505891e+06   
2                          5.13     36882.159400  1.058988e+06   
3                          3.26     34310.242831  1.260617e+06   
4                          4.23     26354.109472  6.309435e+05   

                                             Address  
0  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1  188 Johnson Views Suite 079\nLake Kathleen, CA...  
2  9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                          USS Barnett\nFPO AP 44820  
4                         USNS Raymond\nFPO AE 09386

In [27]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
 5   Price                         5000 non-null   float64
 6   Address                       5000 non-null   object 
dtypes: float64(6), object(1)
memory usage: 273.6+ KB


In [28]:
#finding dependent and independent variable
x = dataset.drop(['Price','Address'],axis=1)
y = dataset.Price

In [29]:
x.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   
4      59982.197226             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population  
0                          4.09     23086.800503  
1                          3.09     40173.072174  
2                          5.13     36882.159400  
3                          3.26     34310.242831  
4                          4.23     26354.109472

In [30]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
dtypes: float64(5)
memory usage: 195.4 KB


In [9]:
y.head()

0    1.059034e+06
1    1.505891e+06
2    1.058988e+06
3    1.260617e+06
4    6.309435e+05
Name: Price, dtype: float64

In [11]:
y.shape

(5000,)

In [31]:
#splitting data for train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)

In [13]:
len(x_train)

3750

In [14]:
len(x_test)

1250

In [32]:
#preprocessing -scaling the data using standard scalar
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()  
x_train = sc.fit_transform(x_train)   
x_test = sc.transform(x_test)

In [16]:
x_train[:5]

array([[-0.90362221, -0.10506927,  0.23797116,  2.04017817, -0.25876232],
       [-0.607347  ,  1.05371068, -1.41402137, -0.65777366,  0.66351887],
       [ 0.25207758,  0.32864587, -0.57599711,  0.38240054, -0.73313626],
       [ 1.03399102, -0.75405832, -1.1231034 , -1.51916792,  0.75363296],
       [ 0.58376203,  0.26620396,  0.70299114,  1.68261829,  0.46547969]])

In [17]:
x_test[:5]

array([[ 0.6041323 ,  0.76127311, -0.37850776,  0.09797791,  0.67282267],
       [ 0.71481928,  0.17222204,  0.1835879 , -0.53587824,  0.89518227],
       [-0.09207018, -0.17149834, -1.91249939,  0.14673607, -0.08459816],
       [-0.15698404, -1.24107837, -1.10340249, -1.53542064,  0.56769854],
       [-0.32100434,  0.29200622,  1.03575498,  0.39865326, -1.00462261]])

In [33]:
#creating a linear regression model
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)


LinearRegression()

In [37]:
#predicting the test data
y_pred = model.predict(x_test)

In [41]:
len(y_pred)

1250

In [42]:
y_test

398     8.942511e+05
3833    9.329794e+05
4836    9.207479e+05
4572    6.918549e+05
636     7.327332e+05
            ...     
465     2.469066e+06
2670    1.443842e+06
37      1.081150e+06
3081    1.313128e+06
2287    9.852839e+05
Name: Price, Length: 1250, dtype: float64

In [43]:
model.score(x_train,y_train)

0.9178295147343559

In [46]:
model.score(x_test,y_test)

0.918508746677807

In [47]:
model.predict([[79545.458574,5.682861,7.009188,4.09,23086.800503]])

array([2.18650335e+10])